import React from "react";

export default function Experiences() {
  return (
    <section class="section dark-section">
      <div class="container">
        <div class="row justify-content-center section-title">
          <div class="col-lg-7 text-center">
            <h2>My Experiences</h2>
          </div>
        </div>
        <div class="row justify-content-right">
        <div class="col-md-6 m-15px-tb">
            <div class="feature-box-2">
              <h5>Valvoline LLC, Lexington, Kentucky</h5>
              <em><p>Software Engineering Intern</p></em>
              <ul>
                <li>Worked as a Full-stack Developer in Modernize Tech team migrating an old Web Application using Vanilla JavaScript to an Angular application called Central</li>
                <li>Wrote, developed, and debugged Spring MVC Rest API that migrate internal employee data to the Oracle database</li>
                <ul>
                  <li>parsed employee data from excel sheets to Java Bean, covert them to JSON objects, and use ResponseEnity to manipulate HTTP response</li>
                  <li>resulted in 30% more Valvoline Corporate Employees having access to Central</li>
                </ul>
                <li>Wrote SQL script to fix 200MB of incorrect data in the Oracle database generated by API errors</li>
                <li>Wrote tests with Cypress and Gherkin to automate the Angular application’s end-to-end testing </li>
                <ul>
                  <li>o	resulted in 10% less manual integration testing for the QA team</li>
                </ul>
              </ul>
            </div>
          </div>
          <div class="col-md-6 m-15px-tb">
            <div class="feature-box-2">
              <h5>University of Kentucky Department of Computer Science</h5>
              <em><p>Web Programming Undergraduate Teaching Assistant</p></em>
             <ul>
               <li>Grade and provide feedback on programming homework and assignments for Professor Ethan Toney </li>
               <li>Tutor students by emphasizing the understanding of topics and assisting with web technologies (React for the frontend and Express for the backend)</li>
             </ul>
            </div>
          </div>
         
          <div class="col-md-6 m-15px-tb">
            <div class="feature-box-2">
              <h5>University of Kentucky International Center</h5>
              <em><p>International Ambassador</p></em>
              <ul>
                <li>Making promotional and interviewing videos for UK international center</li>
                <li>Sending weekly emails to prospective students</li>
                <li>Assisting international applicants to go through the application process and apply for available scholarships</li>
                <li>Reaching out to prospective students from the home country Vietnam by holding workshops and Q&A sessions</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
